### ISSUE TITLE
button control scenes

### ISSUE THREAD

**Issue by KayCox** [toblum/McLighting#307] opened 2019-01-07 18:38 UTC
Is there any possibility for the button control to add an effect ending in the new state? If solid green is active (short press from code below) and medium press is done to go to solid red (code below) that it does not switch instantly but is fading to the new color or doing "fireworks random" or any other effect for just a few seconds and then going to the next state?  How does that look in code? Please help me ;)

// Button handling
#ifdef ENABLE_BUTTON
  #define BTN_MODE_SHORT "STA| 1|  0|245|196|0|255|0"   // Static green 
  #define BTN_MODE_MEDIUM "STA| 1| 0|245|196|255|0|0"   // Static red 
  #define BTN_MODE_LONG "STA| 1| 46|253|196|255|102|  0"  // Fireworks random

**Comment by debsahu** [comment] 2019-01-24 21:21
duplicate of https://github.com/toblum/McLighting/issues/308

**Closed by debsahu** 2019-01-24 21:21 UTC
