### ISSUE TITLE
google assistant 

### ISSUE THREAD

**Issue by cjs1502** [toblum/McLighting#193] opened 2018-06-20 15:01 UTC
how can i use google assistant to turn on/off led?
i dont see any tutorial or anything that explains it.
p.s. i am newbie at this

**Comment by debsahu** [comment] 2018-06-20 15:11
closing duplicate of https://github.com/toblum/McLighting/issues/185 . There are currently no tutorials specifically for McLighting.

**Closed by debsahu** 2018-06-20 15:11 UTC
