### ISSUE TITLE
Nothing wrong but 

### ISSUE THREAD

**Issue by gabenthegamer** [toblum/McLighting#141] opened 2018-04-18 17:33 UTC
Some more questions. Will this work?
https://banggood.app.link/yPmRiiZNdM
What do I need to solder? And if I need external power how do I do that? Just link everything I need😀 Preferably on banggood

**Comment by debsahu** [comment] 2018-04-18 18:46
Duplicate of https://github.com/toblum/McLighting/issues/139 Closing.

**Closed by debsahu** 2018-04-18 18:46 UTC
